### ISSUE TITLE
Where is the .exe?

### ISSUE THREAD

**Issue by isaacweber613** [BestOwl/MyPhone#25] opened 2023-01-13 04:23 UTC
yes i really want to use this app how do i find the exe file or if its not an exe file where do you ahve exact instructions how to install this 
PLEASE HELP

**Comment by wes1993** [comment] 2023-01-13 07:30
Hello,
You can use the intel unison to do the same thing.
Search on Google Intel Unison, you need to download the app from iOS App Store and from Microsoft store, you can use this link on chrome:

ms-windows-store://pdp/?ProductId=9PP9GZM2GN26

Bye
Stefano

**Comment by Zbluu** [comment] 2023-01-13 08:01
Thank you for Unison, I finally have a solution!

**Comment by BestOwl** [comment] 2023-03-11 12:40
This app is still under development. Once we implement all the features we planned, you can find the download links on README.md. Closing as duplicate of #11.

**Closed as not planned by BestOwl** 2023-03-11 12:40 UTC
